### PR TITLE
Introduce multi instance capability

### PR DESCRIPTION
**Pull request by alperaltuntas**
This PR introduces the ability to run multiple instances of MOM6 in CESM. This is required for ensemble runs, and DART, in particular. The main changes are in buildnml to accomodate multiple MOM6 runtime parameter files, MOM_input, MOM_override, diag_table, and input.nml.

This PR should be evaluated in conjunction with https://github.com/NCAR/MOM6/pull/241

### CODE REVIEW

**Comment by gustavo-marques** [comment]
@alperaltuntas; I run a test with `NINST_OCN=4` and got only one file per diag stream (e.g., casename.mom6.sfc_0001_01.nc). Is this expected? I do see four copies of the log files and MOM input files...

**Review by gustavo-marques — APPROVED** [review]

**Comment by gustavo-marques** [comment]
I am still getting only one file per diag stream of MOM6 (e.g., casename.mom6.sfc_0001_01.nc).

**Comment by gustavo-marques** [comment]
Here is the case I ran:
/glade/scratch/gmarques/gmom.e23.GJRA.TL319_t061_zstar_N65.dev_ncar_04may23/run

**Comment by alperaltuntas** [comment]
Can you try it with FMS2? 

`./xmlchange MOM6_INFRA_API=FMS2`

**Comment by gustavo-marques** [comment]
It worked with `MOM6_INFRA_API=FMS2`.

**Comment by klindsay28** [comment]
I'm now seeing that my mods for CESM filenames has a conflict with this that I'll need to resolve when I merge the new `main` to my branch. This makes me wonder if we should add a test of multi instance to aux_mom, to make sure that this capability doesn't get broken.

**Comment by alperaltuntas** [comment]
Interesting. I am getting multiple ocn log files: 

/glade/scratch/altuntas/g.e23.G_JRA.TL319_t061.multi.012/run

I'll investigate why you only get one.

**Comment by klindsay28** [comment]
My case has now run for 2 months and is at
`RUNDIR=/glade/scratch/klindsay/g.e23b12.GMOM_JRA.TL319_t061.003/run`

Your case used `cmeps0.14.2`, while mine used `cmeps0.14.24` and Gustavo's used `cmeps0.14.14`.
I haven't dug into the changes in CMEPS between these tags yet.

**Pull request merged**
