### PR TITLE
Improve reading in key=value from MOM_input/user_nl_mom files

### PR DESCRIPTION
**Pull request by alperaltuntas**
Use a regex expression to check whether a line in MOM_input|MOM_override|user_nl_file is a key=value pair, i.e., a variables assignment. Instead of split('=') and join, look for the first occurence of '=' to prevent disapperance of other '=' occurences in value strings.

Fixes: #93

### CODE REVIEW

**Comment by klindsay28** [comment]
I'm curious, in what circumstances does `re.search("^\s*\w*\s*=\s*.", line_j)` differ from `("=" in line_j)`? I'm not very familiar with regex syntax.

**Comment by alperaltuntas** [comment]
That regex ensures that there is a single word before the `=` operator and some characters after `=`. So it makes sure that the line indeed constists of `key = val` pairs, whereas `("=" in line_j)` checks only if there is `=` in the line, which isn't sufficient to conclude whether the line is a valid parameter assignment or not.

**Comment by alperaltuntas** [comment]
That said, the regex should further be improved as follows `"^\s*\w*\s*=\s*\S+`, so as to make sure that some *non-whitespace* character trails `=`. I will update the pr.

**Comment by alperaltuntas** [comment]
Better yet, the following ensures that the first non-whitespace character following `=` is not `!` (i.e., a comment):
`"^\s*\w*\s*=\s*[^ \t\n\r\f\v!]+"`

**Comment by alperaltuntas** [comment]
This PR is now ready to be merged. Unless anyone has suggestions/objections, I will merge this PR sometime today.

**Review by mnlevy1981 — APPROVED** [review]
I tested this change before 13ab246 and was happy with it, and eyeballing the difference in that commit I don't have any issues with the re changes. I like the new testmod as well.

**Pull request merged**
