### PR TITLE
Fix rpointer check in buildnml

### PR DESCRIPTION
**Pull request by alperaltuntas**
Account for date stamps while checking whether rpointer files exist.

### CODE REVIEW

**Review by mnlevy1981 — CHANGES_REQUESTED** [review]
Have you talked to @jedwards4b about what should be expected? I think we want to continue to support the old file format (e.g. restarting from CESM2 case with `rpointer.ocn` and no date stamp), and we also probably want to make sure a specific restart file has been created rather than looking for anything that fits the `rpointer.ocn.YYYY-MM-DD-SSSSS` pattern. If CESM is trying to restart from 0001-01-07-00000 and the only ocean rpointer file is `rpointer.ocn.0001-01-06-00000` then we should catch that in `buildnml`

**Comment by jedwards4b** [comment]
@alperaltuntas I have a fix for Mike's comment that I can push to your branch if you like?

**Comment by mnlevy1981** [comment]
> This works, you can also get the precise datestamp with:
> 
> ```
>    drv_ptr = case.get_value("DRV_RESTART_POINTER")                                                                                                              
>       if drv_ptr:                                                                                                                                                  
>           mom_ptr = drv_ptr.replace("cpl","ocn")              
> ```

I like this approach, but my test case doesn't have `DRV_RESTART_POINTER` -- was it added in CIME or in CMEPS? And which tag?

**Comment by jedwards4b** [comment]
Still in a cmeps PR: https://github.com/ESCOMP/CMEPS/pull/500/

**Pull request merged**
