### PR TITLE
Add hires tx0.25v1 grid and improvements in MOM_RPS module

### PR DESCRIPTION
**Pull request by alperaltuntas**
- add tx0.25v1 grid
  - updated MOM_input
  - added PE layout
  - added an SMS test in aux_mom test suite
- improvements in MOM_RPS:
  - enhancements in evaluating expressions and expanding cime params.
  - added yamllint test.

Testing: aux_mom on cheyenne/intel

### CODE REVIEW

**Comment by uturuncoglu** [comment]
Hi Alper, If you don't mind, i just add myself as reviewer to test your branch and to be sure it works in our case and does not need any other modification.

**Comment by alperaltuntas** [comment]
> Hi Alper, If you don't mind, i just add myself as reviewer to test your branch and to be sure it works in our case and does not need any other modification.

Sure, let me know if you run into any issues.

**Comment by uturuncoglu** [comment]
I just need to update buildnml to prevent generating MOM input namelist for FV3GFS. We are using static folder for those namelist options and also FV3GFS and MOM shares same input.nml in the current version of the application.

**Comment by alperaltuntas** [comment]
> I just need to update buildnml to prevent generating MOM input namelist for FV3GFS. We are using static folder for those namelist options and also FV3GFS and MOM shares same input.nml in the current version of the application.

You don't need to update buildnml. Just place your desired version of input.nml in SourceMods/src.mom and buildnml will place that version in RUNDIR.

In the future, we will need to find out a way to synchronize how to generate input.nml

**Comment by alperaltuntas** [comment]
@gustavo-marques do NOT merge this yet.

**Comment by uturuncoglu** [comment]
It seems fine to me but what about having same input.nml for both MOM and FV3GFS. In our case input.nml is also modified by FV3GFS's buldnml based on selected number of processor and decomposition parameters. So, we need to place namelist files under SourceMod every time when we run the model with FV3GFS and also for different initial conditions.

**Comment by alperaltuntas** [comment]
Can you point me to FV3GFS's buldnml or describe how it generates input.nml? Maybe we can easily mimic what they do through our MOM_RPS module.

**Comment by uturuncoglu** [comment]
FV3GFS interface is here

https://github.com/ESCOMP/fv3gfs_interface

and buildnml is in

https://github.com/ESCOMP/fv3gfs_interface/blob/cmeps_v0.4.3/cime_config/buildnml

**Comment by alperaltuntas** [comment]
I just looked through fv3gfs buildnml and I feel like input.nml should actually be staged by FMS_interface, and not by MOM_interface or fv3gfs_interface, mainly because input.nml is actually an FMS input file and letting FMS stage input.nml looks like the best way to avoid conflicts between components using FMS. @uturuncoglu Do you agree? Any comments from @mvertens and @jedwards4b is welcome.

Looks like, fv3gfs version of generating input.nml is more involved, so I suggest moving the relevant fv3gfs_interface functions to FMS_interface. I can then incorporate the MOM_interface function that stages input.nml with a PR to FMS_interface.

If this is too much work in the short term, I'd suggest sticking to SourceMods for now.

**Comment by uturuncoglu** [comment]
I think that the easiest way to create another MOM_interface branch and make modifications over there (so, my last commit can be done in there). The FV3GFS interface is still not generic and depends on static namelist files. We are just modifying couple of them related with the selected number of PET. By this way we don't need to modify master. We have already support for tx0.25v1 and that is great.

**Comment by alperaltuntas** [comment]
@gustavo-marques this is ready to be merged.

**Pull request merged**
