### PR TITLE
Discard undetermined expandable vars to be dropped

### PR DESCRIPTION
**Pull request by alperaltuntas**
This PR allows MOM_RPS module to defer the expansion of undetermined expandable variables if they are to be dropped when guards are evaluated, i.e., if they are not necessary for a particular case configuration.

testing: aux_mom.cheyenne

@gustavo-marques can you confirm that this fixes your issue with the regional setup?

### CODE REVIEW

**Comment by kshedstrom** [comment]
For me, the error changed and is now:
```
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 178, in _expand_case_var
    raise RuntimeError("The param "+expandable_param+" is not a CIME xml"
RuntimeError: The param INIT_LAYERS_FROM_Z_FILE is not a CIME xml variable for this case
```
Before it was complaining about `The param TEMP_SALT_Z_INIT_FILE is not a CIME xml variable for this case`, but
both are in the same section of the xml file.

**Comment by gustavo-marques** [comment]
I getting the same error as @kshedstrom 

```
   Calling /glade/scratch/gmarques/CESM_2.2_Kate/components/mom//cime_config/buildnml
Traceback (most recent call last):
  File "./case.build", line 165, in <module>
    _main_func(__doc__)
  File "./case.build", line 160, in _main_func
    use_old=use_old, ninja=ninja, dry_run=dry_run)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 728, in case_build
    return run_and_log_case_status(functor, cb, caseroot=caseroot)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1768, in run_and_log_case_status
    rv = func()
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 722, in <lambda>
    save_build_provenance, use_old, ninja, dry_run)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 662, in _case_build_impl
    model_only, buildlist)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 326, in _build_checks
    case.create_namelists()
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 91, in create_namelists
    (self, caseroot, compname), case=self)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 413, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom//cime_config/buildnml", line 157, in buildnml
    prep_input(case)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom//cime_config/buildnml", line 91, in prep_input
    input_data_list.write(input_data_list_dest, case, MOM_input_final)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/FType_input_data_list.py", line 10, in write
    self.expand_case_vars(case, MOM_input_final)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 224, in expand_case_vars
    self._data[_expand_key(key, val)] = val
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 211, in _expand_key
    val[_expand_key(key_, val_)] = val_
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 211, in _expand_key
    val[_expand_key(key_, val_)] = val_
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 213, in _expand_key
    return _expand_case_var(key)
  File "/glade/scratch/gmarques/CESM_2.2_Kate/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 178, in _expand_case_var
    raise RuntimeError("The param "+expandable_param+" is not a CIME xml"
RuntimeError: The param INIT_LAYERS_FROM_Z_FILE is not a CIME xml variable for this case
```

**Comment by alperaltuntas** [comment]
working on it...

**Comment by alperaltuntas** [comment]
@gustavo-marques @kshedstrom can you try again with the latest commits?

**Comment by gustavo-marques** [comment]
It works now, thanks @alperaltuntas

**Comment by kshedstrom** [comment]
I on the other hand added my grids to the input_data_list.yaml and input_data_list.json and I get:
```
Traceback (most recent call last):
  File "case.build", line 165, in <module>
    _main_func(__doc__)
  File "case.build", line 160, in _main_func
    use_old=use_old, ninja=ninja, dry_run=dry_run)
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 728, in case_build
    return run_and_log_case_status(functor, cb, caseroot=caseroot)
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1768, in run_and_log_case_status
    rv = func()
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 722, in <lambda>
    save_build_provenance, use_old, ninja, dry_run)
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 662, in _case_build_impl
    model_only, buildlist)
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 326, in _build_checks
    case.create_namelists()
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 91, in create_namelists
    (self, caseroot, compname), case=self)
  File "/glade/u/home/kate/CESM_2.2/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 413, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/glade/u/home/kate/CESM_2.2/components/mom//cime_config/buildnml", line 157, in buildnml
    prep_input(case)
  File "/glade/u/home/kate/CESM_2.2/components/mom//cime_config/buildnml", line 91, in prep_input
    input_data_list.write(input_data_list_dest, case, MOM_input_final)
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/FType_input_data_list.py", line 13, in write
    self.infer_values(case)
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 325, in infer_values
    _determine_value_recursive(self._data)
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 309, in _determine_value_recursive
    _determine_value_recursive(entry[child])
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 307, in _determine_value_recursive
    _determine_value_recursive(entry)
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 304, in _determine_value_recursive
    entry[child] = _do_determine_value(entry[child])
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 263, in _do_determine_value
    if _check_guard_satisfied(value_guard, case):
  File "/glade/u/home/kate/CESM_2.2/components/mom/cime_config/MOM_RPS/MOM_RPS.py", line 241, in _check_guard_satisfied
    "variable(s) is defined for this case configuration and that "
RuntimeError: The guard "$INIT_LAYERS_FROM_Z_FILE" == "True" has an expandable case variable that couldn't be determined. Make sure that the expandable variable(s) is defined for this case configuration and that expand_case_vars is called before infer_values method.
```

**Comment by alperaltuntas** [comment]
@kate, you should add your grids to the `tempsalt` entry of `input_data_list.yaml` only if your grids require a `TEMP_SALT_Z_INIT_FILE`. If that's the case, then you should add your grids in `INIT_LAYERS_FROM_Z_FILE` entry inside MOM_input.yaml as well, as follows:

```
    INIT_LAYERS_FROM_Z_FILE:
        description: |
            "[Boolean] default = False
            If true, intialize the layer thicknesses, temperatures,
            and salnities from a Z-space file on a latitude-
            longitude grid."
        datatype: logical
        units: Boolean
        value:
            $OCN_GRID == "gx1v6": True
            $OCN_GRID == "tx0.66v1": True
            $OCN_GRID == "tx0.25v1": True
            $OCN_GRID == "Bering": True
            $OCN_GRID == "Arctic5": True

```

or more concisely:
```
        value:
            $OCN_GRID in ["gx1v6", "tx0.66v1", "tx0.25v1", "Bering", "Arctic5"] : True
```

**Comment by alperaltuntas** [comment]
Additionally, you'd need to add your grids to the following MOM_input.yaml entry in addition to INIT_LAYERS_FROM_Z_FILE:
TEMP_SALT_Z_INIT_FILE

**Comment by kshedstrom** [comment]
Nope, still getting the same error.

**Comment by alperaltuntas** [comment]
Looks like you have your own copy of MOM_input in your SourceMods, which is overriding the default one. You need to add INIT_LAYERS_FROM_Z_FILE and TEMP_SALT_Z_INIT_FILE to SourceMods/src.mom/MOM_input file.

**Comment by kshedstrom** [comment]
Ah, right you are - it didn't occur to me that you were adding options to MOM_input.

Now I'm running into gnu issues:
```
mpif90  -c -I/glade/u/home/kate/CESM_2.2/cime/src/share/timing  -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fcray-pointer   -O  -I/glade/p/cesmdata/cseg/PROGS/esmf/8.1.0b23/mpt/2.21/intel/19.0.5/mod/modO/Linux.intel.64.mpt.default -I/glade/p/cesmdata/cseg/PROGS/esmf/8.1.0b23/mpt/2.21/intel/19.0.5/include -I/glade/u/apps/ch/opt/netcdf-mpi/4.7.3/mpt/2.21/intel/19.0.5/include -I/glade/u/apps/ch/opt/netcdf-mpi/4.7.3/mpt/2.21/intel/19.0.5/include   -DCESMCOUPLED   -DHAVE_NANOTIME -DBIT64 -DHAVE_VPRINTF -DHAVE_BACKTRACE -DHAVE_SLASHPROC -DHAVE_COMM_F2C -DHAVE_TIMES -DHAVE_GETTIMEOFDAY   -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU -DNUOPC_INTERFACE -DHAVE_MPI -ffree-form   /glade/u/home/kate/CESM_2.2/cime/src/share/timing/perf_mod.F90
/glade/u/home/kate/CESM_2.2/cime/src/share/timing/Makefile:87: recipe for target 'perf_mod.o' failed
gmake: Leaving directory '/glade/scratch/kate/Bering_JRA_2.2/bld/gnu/mpt/nodebug/nothreads/nuopc/gptl'
/glade/u/home/kate/CESM_2.2/cime/src/share/timing/perf_utils.F90:21:7:

   21 |    save
      |       1
Warning: Legacy Extension: Blanket SAVE statement at (1) follows previous SAVE statement
f951: Fatal Error: Reading module ‘esmf’ at line 1 column 2: Unexpected EOF
compilation terminated.
gmake: *** [perf_mod.o] Error 1
ERROR: /glade/u/home/kate/CESM_2.2/cime/src/share/timing/perf_utils.F90:21:7:

   21 |    save
      |       1
Warning: Legacy Extension: Blanket SAVE statement at (1) follows previous SAVE statement
f951: Fatal Error: Reading module  esmf  at line 1 column 2: Unexpected EOF
```
I'll try to work through these. Thanks!

**Comment by kshedstrom** [comment]
I should note that I was trying the gnu compiler option. I can back off to intel for now. In the past, I failed to get intel and MOM6 to play nice on the chinook computer, but they recently installed a new intel version to try.

**Comment by gustavo-marques** [comment]
@kshedstrom, I was able to compile (with intel) without making any changes in /glade/u/home/kate/CESM_2.2/components/mom/
Unless you are still having trouble compiling, I will merge this PR. Please let us know.

**Comment by kshedstrom** [comment]
Nope, no more troubles compiling. Thanks!

**Pull request merged**
