### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by alperaltuntas**
- [set AUTO_MASKTABLE to True for 2/3 and 1/4 deg grids](https://github.com/ESCOMP/MOM_interface/commit/b72d7366e7a9e067b7775fa799ea0f09fca143fe)
- [remove cheyenne from config_pes and testlists](https://github.com/ESCOMP/MOM_interface/commit/123e27e871b7af0e52fae54570c0253c07ca07ae)
- [update all JRA compsets to v1.4, add a JRA-RYF compset](https://github.com/ESCOMP/MOM_interface/commit/9798d38bf6f30bb0a50019f057f5844fd4caa0dc)
- [more test changes: add more prealpha/prebeta tests](https://github.com/ESCOMP/MOM_interface/commit/62b1b90318be0e8050a89c5751db44bc55278f3e)

This PR changes answers. testing: aux_mom.derecho

### CODE REVIEW

**Comment by alperaltuntas** [comment]
TODO: We also need to update the standalone build script and templates. @mnlevy1981 ?

**Review by klindsay28 — APPROVED** [review]
It looks like you have removed most, but not all, tests on the `t061` grid. Do we need/want to be running tests on this grid? Besides this question the PR looks good to me.

**Comment by alperaltuntas** [comment]
> It looks like you have removed most, but not all, tests on the `t061` grid. Do we need/want to be running tests on this grid? Besides this question the PR looks good to me.

There are two remaining t061 tests in aux_mom:
- ERS.T62_t061.GMOM_JRA
- ERS.TL319_t061_wt061.GMOM_JRA_WD

I think we should maintain the former test for as long as t061 is still an option. We may remove it if and when we decide to remove the t061 grid all together. Regarding the latter test, it corresponds to the wave-coupled compset. We haven't switched to the new grid for this compset yet, but I will update the test once we make that transition.

**Comment by gustavo-marques** [comment]
This PR will break our current diagnostics because the grid metrics are read from the static file. Before merging this PR, I suggest we discuss a plan going forward for supporting/providing the grid metrics for the 2/3 and 1/4 deg grids.

**Review by gustavo-marques — APPROVED** [review]

**Comment by alperaltuntas** [comment]
> This PR will break our current diagnostics because the grid metrics are read from the static file. Before merging this PR, I suggest we discuss a plan going forward for supporting/providing the grid metrics for the 2/3 and 1/4 deg grids.

Can the diagnostics tools be reconfigured to read in the grid metrics from the ocean_hgrid (supergrid) file instead?

**Pull request merged**
