### PR TITLE
Update stochastic physics

### PR DESCRIPTION
**Pull request by mnlevy1981**
This MOM6 tag adds a dummy cap for [`stochastic_physics`](https://github.com/iangrooms/stochastic_physics/tree/ocn_skeb_240709); this PR adds the actual library as `externals/stochastic_physics`. The default will be `DO_SKEB = False` (do not use this packge), but `input.nml` will contain default values so users can turn it on simply by adding `DO_SKEB = True` to `user_nl_mom`. There is also a new variable in `env_build.xml` (`MOM6_BUILD_STOCH_PHYSICS`) that will let the test suite build with the dummy cap instead of the full cap, which is useful for ensuring we are not breaking the stand-alone MOM6 build.

### CODE REVIEW

**Comment by mnlevy1981** [comment]
As of ba1ad27 there is only one issue with this PR: when `DO_SKEB = True`, the model does not restart exactly*. We need to have `mom_cap.F90` call `ocean_model_restart()` with the optional `stoch_restartname` argument, and then make sure that `write_stoch_restart_ocn()` gets called. There are probably also steps to take to make sure the stoch restart file gets archived (and staged in branch files). If we're okay with the ERS test I added to `aux_mom` that turns on SKEB failing, we can merge this in and then try to fix the failing test later.

\* by default `DO_SKEB = False` and the model still restarts exactly in that configuration.

**Comment by alperaltuntas** [comment]
@mnlevy1981, when I manually enter this PR branch into `.gitmodules` and execute the `git-fleximod update mom` command, I end up with an empty `externals/stochastic_physics/` directory. Am i missing something?

**Comment by mnlevy1981** [comment]
> @mnlevy1981, when I manually enter this PR branch into `.gitmodules` and execute the `git-fleximod update mom` command, I end up with an empty `externals/stochastic_physics/` directory. Am i missing something?

Do you know what version of git fleximod you're using? I did my testing in a `cesm3_0_beta01` tag, but needed to update to the latest git fleximod because I was also getting an empty directory. I think it was maybe something similar to https://github.com/ESMCI/git-fleximod/issues/50, and whatever got fixed addressed what I was seeing as well. According to github [the submodule is linked to the right commit](https://github.com/mnlevy1981/MOM_interface/tree/mi_240522_stochGME/externals), so I think everything in `.gitmodules` is correct. @jedwards4b have you seen something like this while trying to add a new submodule?

**Comment by jedwards4b** [comment]
I'm not sure why but it appears that the alpha02a tag that was created did not contain all of the changes I had specified.  In particular git-fleximod is not at the latest version.

**Comment by alperaltuntas** [comment]
@mnlevy1981, Have you assessed the impact of enabling MOM6_BUILD_STOCH_PHYSICS=True on build time? If it's significant, we should consider enabling it only when necessary. Additionally, instead of creating a separate mom/no_stoch_physics test, could we integrate that test mod into an existing test to reduce the number of additional tests from 2 to 1? Also, given the incompatibility with git-fleximod, I am uncertain about the timing for a full review and merge of this PR.

**Comment by mnlevy1981** [comment]
`stochastic_physics` is a small package, and has minimal impact on build time. Here's the most recent build times:

* Not building the package: 11:38 to build CESM, 2:03 to build mom6
* Building the package: 14:44 to build CESM, 2:02 to build mom6

The 3 minute jump in CESM build-time looked concerning until I checked the per-component times and realized that the mom6 build time didn't change. I'm rebuilding both cases now, and will come back with a second set of numbers to maybe get a better idea of machine-induced variance.

I think it makes sense to add two tests, because @iangrooms wants the default behavior to be "build `stochastic_physics` but don't turn it on". We need to make sure "don't build `stochastic_physics`" works because that's the build path the rest of the MOM6 community will be using, and we also want to test running with the new package turned on. There aren't many defined test cases -- I see `bcompset`, `cfc_mods`, `debug`, and `rps`; I think we want the B compset, CFC, and debug tests to build the default configuration, and I don't know what the RPS test is but I assume it would also be a weird spot to stack a second test. If you are worried about the cost of the additional tests, maybe we should move one (or both) out of `aux_mom`? I could see putting them both in `pr_mom` or maybe even one in `pr_mom` and the other in `prealpha` or `prebeta`.

For testing, maybe @jedwards4b or @fischer-ncar could let us know when [`cesm:main`](https://github.com/ESCOMP/cesm) has been updated and you could create a sandbox somewhere between alpha02a and alpha02b? Alternatively, I checked out `cesm3_0_beta01` and then replaced [`.lib/git-fleximod`](https://github.com/ESCOMP/CESM/tree/master/.lib/git-fleximod) with a clean checkout of https://github.com/ESMCI/git-fleximod before running `bin/git-fleximod`

**Comment by mnlevy1981** [comment]
Round two of timing the build:

* Building `stochastic_physics`: 13:30 to build CESM, 2:03 to build mom6
* Not building `stochastic_physics`: 12:45 to build CESM, 2:02 to build mom6

Combined with the timings from the first comment, it really does seem to be in the noise

**Comment by mnlevy1981** [comment]
Tested this with `aux_mom`, and see expected failures:

```
99	PASS
	7	RUN (PASS)
      1 DIMCS_Ld1.TL319_t232.G_JRA.derecho_intel.mom-cfc_mods--mom-debug
      1 ERI.TL319_t232.G_JRA.derecho_intel.mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
      1 PET.TL319_t232.C_JRA.derecho_intel
      1 SMS_D.TL319_t232.G_JRA_RYF.derecho_intel
      1 SMS_Ld40.TL319_t232.C_JRA.derecho_intel
      1 SMS.T62_t025.C.derecho_intel
	4	BASELINE (PASS)
      1 ERI.TL319_t232.G_JRA.derecho_intel.mom-debug
      1 SMS_D.TL319_t232.G_JRA_RYF.derecho_intel
      1 SMS_Ld40.TL319_t232.C_JRA.derecho_intel
      1 SMS.T62_t025.C.derecho_intel
19	FAIL
	7	NLCOMP (FAIL)
      1 DIMCS_Ld1.TL319_t232.G_JRA.derecho_intel.mom-cfc_mods--mom-debug
      1 ERI.TL319_t232.G_JRA.derecho_intel.mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
      1 PET.TL319_t232.C_JRA.derecho_intel
      1 SMS_D.TL319_t232.G_JRA_RYF.derecho_intel
      1 SMS_Ld40.TL319_t232.C_JRA.derecho_intel
      1 SMS.T62_t025.C.derecho_intel
	3	COMPARE (FAIL)
      1 ERI.TL319_t232.G_JRA.derecho_intel.mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
      1 PET.TL319_t232.C_JRA.derecho_intel
	3	MEMCOMP (FAIL)
      1 DIMCS_Ld1.TL319_t232.G_JRA.derecho_intel.mom-cfc_mods--mom-debug
      1 ERI.TL319_t232.G_JRA.derecho_intel.mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
	2	TPUTCOMP (FAIL)
      1 DIMCS_Ld1.TL319_t232.G_JRA.derecho_intel.mom-cfc_mods--mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
	3	BASELINE (FAIL)
      1 DIMCS_Ld1.TL319_t232.G_JRA.derecho_intel.mom-cfc_mods--mom-debug
      1 ERS.TL319_t232.G_JRA.derecho_intel.mom-with_stoch_physics
      1 PET.TL319_t232.C_JRA.derecho_intel
	1	CREATE_NEWCASE (FAIL)
      1 SMS_Ld2.f09_t232.B1850.derecho_intel.mom-bcompset
```

All the `NLCOMP` failures are due to changes in `MOM_input` and `input.nml` to include a few new parameters and a new namelist, respectively. There isn't a `B1850` compset anymore, but I don't think this PR is the right place to update the testlist. The `ERI` and `PET` tests were failing the `COMPARE` test when generating my baselines, and I think I was a little impatient with the `DIMCS` test and just didn't let the baseline finish running.

As noted above, the new `with_stoch_physics` test does not restart exactly. That can be fixed in a future MOM6 PR.

@iangrooms -- note the commit message from 9774532, running with `DO_SKEB=False` and `SKEB_USE_GM=True` is not supported, so when you want to turn SKEB on you need to add both

```
DO_SKEB=True
SKEB_USE_GM=True
```

in `user_nl_mom` (last time we talked, I thought you just needed to change `DO_SKEB`). @gustavo-marques this is ready for review / merging.

**Pull request merged**
